# Generated by Django 3.0.3 on 2020-05-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'shazam_song',
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=200)),
                ('time_stamp', models.IntegerField()),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shazam.Song')),
            ],
            options={
                'db_table': 'shazam_fingerprint',
            },
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['hash_value'], name='shazam_fing_hash_va_6c7848_idx'),
        ),
    ]
