# Generated by Django 3.0.3 on 2020-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=200)),
                ('song_id', models.IntegerField()),
                ('time_stamp', models.IntegerField()),
            ],
        ),
    ]
